GET http://localhost:5000/api/items
Content-Type: application/json

###

POST http://localhost:5000/api/comments
Content-Type: application/json

{
  "comment": "This post changed my life and my hairline",
  "rating": 5,
  "replies": "Agreed, this is peak content fsho",
  "likes": 42
}

###

PUT http://localhost:5000/api/items/683809d4516e159ec44dd24d
Content-Type: application/json

{
  "commentId": "6838239cc0cec85643ff64ea"
}